### ISSUE TITLE
Exceptions being eaten up

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#231] opened 2019-04-05 01:22 UTC
Sample program which reproduces this problem.

```
import asyncio


async def background_task():
    print("Background task started.")
    raise NotImplementedError


def callback(future):
    if future.done():
        ex = future.exception()
        if ex is not None:
            raise ex


async def _prog():
    task = asyncio.ensure_future(background_task())
    await asyncio.sleep(0.1)
    # task.add_done_callback(callback)
    print("do some computation.")
    task.cancel()

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(_prog())
```

FIX:
Uncommenting this `task.add_done_callback(callback)` will ensure that the exception is raised.

We have a lot of code which just starts a task and then later cancels the task and there are no callbacks which make debugging really hard since the exceptions get eaten up.

**Comment by amiller** [comment] 2019-04-05 01:37
I can imagine two policies then... One is to check that every ensure_future also installs such a call back, another is to await a task after cancelling it.

**Comment by amiller** [comment] 2019-04-05 01:37
Addresses #125

**Comment by smkuls** [comment] 2019-04-07 07:47
Another issue is when you call `asyncio.gather` and some of the tasks fail which could potentially cause the rest of the tasks to not execute causing the gather to hang - again - no exceptions are thrown in this case.

**Comment by Drake-Eidukas** [comment] 2019-04-12 20:40
[(more details)](https://bugs.python.org/issue31452)

**Comment by amiller** [comment] 2019-04-12 22:04
> Another issue is when you call `asyncio.gather` and some of the tasks fail which could potentially cause the rest of the tasks to not execute causing the gather to hang - again - no exceptions are thrown in this case.

Can you elaborate on this and give an example?


> [(more details)](https://bugs.python.org/issue31452)

I think you are saying the above detail would pertain to samarth's example? It seems like that just explains the intended behavior of gather.... if gather fails, because one of the gather'd tasks was cancelled... you may need to gather (or cancel) again

**Comment by Drake-Eidukas** [comment] 2019-04-13 18:16
Yeah, I was posting it in relation to samarth's example.

**Comment by amiller** [comment] 2019-05-05 19:45
When debugging #251 we needed to use the following variation, which prints the exception before raising it (in case the reraise is swallowed too due to do a different mistake):

```python
def callback(future):
    if future.done():
        ex = future.exception()
        if ex is not None:
            print("EX:", ex)
            raise ex
```

**Comment by amiller** [comment] 2019-06-08 15:36
Closing since the workarounds in this thread suffice

**Closed as completed by amiller** 2019-06-08 15:36 UTC
Labels: bug
